### ISSUE TITLE
Warnings in console before every auto-save

### ISSUE THREAD

**Issue by zigazajc007** [Kihsomray/CyberLevels-Standard#3]
```bash
[22:15:11 WARN]: [CLV] Plugin CyberLevels v0.5.8 generated an exception while executing task 1566180
java.lang.NullPointerException: Cannot invoke "net.zerotoil.dev.cyberlevels.objects.leaderboard.LeaderboardPlayer.getUUID()" because "lbp" is null
        at net.zerotoil.dev.cyberlevels.objects.levels.PlayerData.lambda$checkLeaderboard$0(PlayerData.java:221) ~[CyberLevels-0.5.8.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-60]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.1.jar:git-Paper-60]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.1.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[22:15:11 WARN]: [CLV] Plugin CyberLevels v0.5.8 generated an exception while executing task 1566188
java.lang.NullPointerException: Cannot invoke "net.zerotoil.dev.cyberlevels.objects.leaderboard.LeaderboardPlayer.getUUID()" because "lbp" is null
        at net.zerotoil.dev.cyberlevels.objects.levels.PlayerData.lambda$checkLeaderboard$0(PlayerData.java:235) ~[CyberLevels-0.5.8.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-60]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.1.jar:git-Paper-60]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.1.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[22:15:11 WARN]: [CLV] Plugin CyberLevels v0.5.8 generated an exception while executing task 1566190
java.lang.NullPointerException: Cannot invoke "net.zerotoil.dev.cyberlevels.objects.leaderboard.LeaderboardPlayer.getUUID()" because "lbp" is null
        at net.zerotoil.dev.cyberlevels.objects.levels.PlayerData.lambda$checkLeaderboard$0(PlayerData.java:235) ~[CyberLevels-0.5.8.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-60]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.1.jar:git-Paper-60]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.1.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[22:15:11 WARN]: [CLV] Plugin CyberLevels v0.5.8 generated an exception while executing task 1566186
java.lang.NullPointerException: Cannot invoke "net.zerotoil.dev.cyberlevels.objects.leaderboard.LeaderboardPlayer.getUUID()" because "lbp" is null
        at net.zerotoil.dev.cyberlevels.objects.levels.PlayerData.lambda$checkLeaderboard$0(PlayerData.java:221) ~[CyberLevels-0.5.8.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-60]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.1.jar:git-Paper-60]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.1.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[22:15:11 WARN]: [CLV] Plugin CyberLevels v0.5.8 generated an exception while executing task 1566192
java.lang.NullPointerException: Cannot invoke "net.zerotoil.dev.cyberlevels.objects.leaderboard.LeaderboardPlayer.getUUID()" because "lbp" is null
        at net.zerotoil.dev.cyberlevels.objects.levels.PlayerData.lambda$checkLeaderboard$0(PlayerData.java:221) ~[CyberLevels-0.5.8.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-60]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.1.jar:git-Paper-60]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.1.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[22:15:14 INFO]: [CLV] §aSuccessfully auto-saved all player data (§751ms§a).
```

Those warnings are thrown before every auto-save.

**Comment by Klema4** [comment]
Hey there!
Try disabling instant-update option in config.yml.
0.5.9 should fix this problem by default.
