### ISSUE TITLE
I'm having some problems, can you help me?

### ISSUE THREAD

**Issue by Cqmmls** [Kihsomray/CyberLevels-Standard#7]
[15:02:11 INFO]: [CLV] Enabling CyberLevels v0.5.9
[15:02:11 ERROR]: Error occurred while enabling CyberLevels v0.5.9 (Is it up to date?)
java.lang.NoClassDefFoundError: org/apache/commons/lang3/SystemUtils
        at net.zerotoil.dev.cyberlevels.CyberLevels.reloadClasses(CyberLevels.java:61) ~[CyberLevels-0.5.9.jar:?]
        at net.zerotoil.dev.cyberlevels.CyberLevels.onEnable(CyberLevels.java:38) ~[CyberLevels-0.5.9.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Sugarcane-1.17.1/dev-115]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Sugarcane-1.17.1/dev-115]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Sugarcane-1.17.1/dev-115]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:562) ~[patched_1.17.1.jar:git-Sugarcane-1.17.1/dev-115]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:476) ~[patched_1.17.1.jar:git-Sugarcane-1.17.1/dev-115]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:736) ~[patched_1.17.1.jar:git-Sugarcane-1.17.1/dev-115]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:362) ~[patched_1.17.1.jar:git-Sugarcane-1.17.1/dev-115]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1237) ~[patched_1.17.1.jar:git-Sugarcane-1.17.1/dev-115]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[patched_1.17.1.jar:git-Sugarcane-1.17.1/dev-115]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang3.SystemUtils
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:153) ~[patched_1.17.1.jar:git-Sugarcane-1.17.1/dev-115]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:105) ~[patched_1.17.1.jar:git-Sugarcane-1.17.1/dev-115]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        ... 12 more
[15:02:11 INFO]: [CLV] Disabling CyberLevels v0.5.9
[15:02:11 ERROR]: Error occurred while disabling CyberLevels v0.5.9 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "net.zerotoil.dev.cyberlevels.objects.levels.LevelCache.saveOnlinePlayers(boolean)" because "this.levelCache" is null
        at net.zerotoil.dev.cyberlevels.CyberLevels.onDisable(CyberLevels.java:114) ~[CyberLevels-0.5.9.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[patched_1.17.1.jar:git-Sugarcane-1.17.1/dev-115]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[patched_1.17.1.jar:git-Sugarcane-1.17.1/dev-115]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[patched_1.17.1.jar:git-Sugarcane-1.17.1/dev-115]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374) ~[patched_1.17.1.jar:git-Sugarcane-1.17.1/dev-115]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Sugarcane-1.17.1/dev-115]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:562) ~[patched_1.17.1.jar:git-Sugarcane-1.17.1/dev-115]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:476) ~[patched_1.17.1.jar:git-Sugarcane-1.17.1/dev-115]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:736) ~[patched_1.17.1.jar:git-Sugarcane-1.17.1/dev-115]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:362) ~[patched_1.17.1.jar:git-Sugarcane-1.17.1/dev-115]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1237) ~[patched_1.17.1.jar:git-Sugarcane-1.17.1/dev-115]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[patched_1.17.1.jar:git-Sugarcane-1.17.1/dev-115]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]

**Comment by Cqmmls** [comment]
I've found the reason, the error caused by the plugin starting to load without loading the necessary libs

**Comment by callum5771** [comment]
This seems to be an issue restricted to 1.17 versions of Minecraft - I had this issue too. Had to downgrade to the 0.5.8 release on that particular server.
